src/Entity/Group.php
<?php

namespace App\Entity;

use App\Repository\GroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GroupRepository::class)]
#[ORM\Table(name: '`group`')]
class Group
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 60)]
    private $name;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $lastArchivedAt;

    #[ORM\Column(type: 'string', length: 255)]
    private $linkToken;

    #[ORM\ManyToOne(targetEntity: Event::class, inversedBy: 'Groups')]
    #[ORM\JoinColumn(nullable: false)]
    private $Event;

    #[ORM\OneToMany(mappedBy: 'idGroup', targetEntity: Ticket::class)]
    private $tickets;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastArchivedAt(): ?\DateTimeInterface
    {
        return $this->lastArchivedAt;
    }

    public function setLastArchivedAt(?\DateTimeInterface $lastArchivedAt): self
    {
        $this->lastArchivedAt = $lastArchivedAt;

        return $this;
    }

    public function getLinkToken(): ?string
    {
        return $this->linkToken;
    }

    public function setLinkToken(string $linkToken): self
    {
        $this->linkToken = $linkToken;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->Event;
    }

    public function setEvent(?Event $Event): self
    {
        $this->Event = $Event;

        return $this;
    }

    public function generateLinkToken(): string
    {
        $linkToken = random_bytes(NB_CHAR_ADMIN_TOKEN);

        return sha1($linkToken);
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): self
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets[] = $ticket;
            $ticket->setIdGroup($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): self
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getIdGroup() === $this) {
                $ticket->setIdGroup(null);
            }
        }

        return $this;
    }
}

src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $request;

    #[ORM\Column(type: 'datetime')]
    private $createAt;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updateAt;

    #[ORM\ManyToOne(targetEntity: Group::class, inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false)]
    private $idGroup;

    #[ORM\ManyToOne(targetEntity: Status::class, inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: true)]
    private $Status;

    #[ORM\ManyToOne(targetEntity: Priority::class, inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false)]
    private $Priority;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRequest(): ?string
    {
        return $this->request;
    }

    public function setRequest(string $request): self
    {
        $this->request = $request;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getIdGroup(): ?Group
    {
        return $this->idGroup;
    }

    public function setIdGroup(?Group $idGroup): self
    {
        $this->idGroup = $idGroup;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->Status;
    }

    public function setStatus(?Status $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getPriority(): ?Priority
    {
        return $this->Priority;
    }

    public function setPriority(?Priority $Priority): self
    {
        $this->Priority = $Priority;

        return $this;
    }
}

src/Controller/GroupController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\Common\Collections\ArrayCollection;

use App\Form\GroupFormType;
use App\Form\NewTicketFormType;

use App\Entity\Group;
use App\Entity\Event;
use App\Entity\Priority;
use App\Entity\Ticket;

class GroupController extends AbstractController
{
    #[Route('/event/{adminToken}/groups/', name: 'event_groups')]
    public function createGroups(ManagerRegistry $doctrine, Request $request, string $adminToken): Response
    {
        $entityManager = $doctrine->getManager();

        $group = new Group();

        $eventId = $request->query->get('eventId');
        $message = $request->query->get('message');

        $repository = $doctrine->getRepository(Event::class);
        $event = $repository->find($eventId);

        $groups = $event->getGroups();
        

        $linkToken = $group->generateLinkToken();

        $form = $this->createForm(GroupFormType::class, $group);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $groupName = $form->get('name')->getData();
            

            $repository = $doctrine->getRepository(Event::class);
            $event = $repository->find($eventId);

            $group->setName($groupName);
            $group->setLinkToken($linkToken);
            $group->setEvent($event);

            $entityManager->persist($group);
            $entityManager->flush();

            return $this->redirectToRoute('event_groups', ['adminToken' => $adminToken, 'eventId' => $eventId, 'message' => $message]);
            
        }

        return $this->renderForm('group/index.html.twig', [
            'form' => $form,
            'groups' => $groups,
            'adminToken' => $adminToken,
            'linkToken' => $linkToken,
            'eventId' => $eventId,
            'message' => $message
        ]);
    }

    #[Route('/event/{adminToken}/groups/remove/', name: 'event_group_remove')]
    public function removeGroup(ManagerRegistry $doctrine, Request $request, string $adminToken): Response
    {
        $groupId = $request->query->get('groupId');
        $eventId = $request->query->get('eventId');

        $repository = $doctrine->getRepository(Group::class);
        $group = $repository->find($groupId);
        $tickets = $group->getTickets();
        

        if($tickets->count() == 0)
        {
            $repository->remove($group);
            $message = "groupe supprimé";
        } else {
            $message = "impossible de supprimer le groupe";
        }
        
        
        

        return $this->redirectToRoute('event_groups', ['adminToken' => $adminToken, 'eventId' => $eventId, 'message' => $message]);        
    }

    #[Route('/group/{linkToken}/', name: 'group_tickets')]
    public function createTicket(ManagerRegistry $doctrine, Request $request, string $linkToken): Response
    {
        $entityManager = $doctrine->getManager();

        $ticket = new Ticket();

        $groupId = $request->query->get('groupId');
        $repository = $doctrine->getRepository(Group::class);
        $group = $repository->find($groupId);
        $event = $group->getEvent();


        $tickets = $group->getTickets();
        
        $form = $this->createForm(NewTicketFormType::class, $ticket);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $ticketRequest = $form->get('request')->getData();
            $priorityLevel = $form->get('Priority')->getData();

            $repository = $doctrine->getRepository(Priority::class);
            $priority = $repository->findOneByWeight($priorityLevel);
            $createAt = new \DateTime();            
            
            $ticket->setPriority($priority);
            $ticket->setRequest($ticketRequest);
            $ticket->setCreateAt($createAt);
            $ticket->setIdGroup($group);
            
            

            $entityManager->persist($ticket);
            $entityManager->flush();

            return $this->redirectToRoute('group_tickets', ['linkToken' => $linkToken, 'groupId' => $groupId]);
            
        }

        return $this->renderForm('group/showGroup.html.twig', [
            'form' => $form,
            'group' => $group,
            'linkToken' => $linkToken,
            'tickets' => $tickets,
            'event' => $event
        ]);
    }

}

templates/group/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GroupController!{% endblock %}
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}
{% block body %}
<section class="my-2 mx-5">
    <h1>Liste des groupes de l'événement</h1>
    {% set hasTickets = false %}
    <div>{{ message }}</div>
    
    {% for group in groups %}
        {% if group.tickets.count() > 0 %}
            {% set hasTickets = true %}
        {% endif %}
    {% endfor %}

    {% if hasTickets %}
        <a href="{{ path('event_tickets', {'eventId': eventId, 'adminToken': adminToken}) }}">Voir les tickets</a>
    {% endif %}
    
</section>

<section class="my-2 mx-5">
    <h2>Groupes :</h2>
    
    {% for group in groups %}
        <div class="my-3">
            <div>{{ group.name }}</div>

            {% if group.lastArchivedAt != NULL %}
                <div>{{ group.lastArchivedAt|date('Y-m-d')  }}</div>
            {% else  %}
                <div>Never helped</div>
            {% endif %}

            <a href="{{ path('group_tickets', {'groupId': group.id, 'linkToken': linkToken}) }}">Voir les tickets du groupe</a>
            <button><a href="{{ path('event_group_remove', {'groupId': group.id, 'eventId': eventId, 'adminToken': adminToken}) }}">Delete</a> </button>
        </div>
    {% endfor %}
</section>

<section class="my-2 mx-5">
    {{ form(form)}}
</section>
{% endblock %}

templates/group/showGroup.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}
{% block body %}
<section class="my-2 mx-5">
    <h1>{{group.name}}</h1>

    {% set nbGroupsBeforeUs = 0 %}
    {% for eventGroup in event.groups %}
        {% for ticket in eventGroup.tickets %}
            {% if ticket.status != NULL and ticket.status.isArchived == false and group.lastArchivedAt < ticket.createAt %}
                {% set nbGroupsBeforeUs = nbGroupsBeforeUs + 1 %}
                {% set break = true %}
            {% endif %}
        {% endfor %}
    {% endfor %}
</section>

<section class="my-2 mx-5">
    <h2>Liste d'attente :</h2>
    <div>{{nbGroupsBeforeUs}}</div>
</section>

<section class="my-2 mx-5">
    <h2>Liste des tickets :</h2>
    {% for ticket in tickets %}
        <div class="my-3">
            <div>{{ ticket.request }}</div>
            {% if ticket.status != NULL %}
                <div>{{ ticket.status.name }}</div>
            {% else %}
                <div>Non traité</div>
            {% endif %}
            <button><a href="{{ path('group_ticket', {'groupId': group.id, 'linkToken': linkToken, 'ticketId': ticket.id}) }}">Voir le ticket</a> </button>
        </div>
    {% endfor %}
</section>

<section class="my-2 mx-5">
    <h2>Création d'un ticket</h2>
    {{ form(form)}}
</section>



{% endblock %}